// Fake data
const VendorList = [
  {
    id: 1,
    name: "ABC Supplies",
    email: "abc@supplies.com",
    phone: 1234567890,
    address: {
      street: "123 Main Street",
      city: "Cityville",
      state: "CALIFORNIA",
      country: "Countryland",
    },
    vendorType: "SUPPLIER",
  },
  {
    id: 2,
    name: "XYZ Corporation",
    email: "xyz@corp.com",
    phone: 9876543210,
    address: {
      street: "456 Elm Street",
      city: "Townville",
      state: "TEXAS",
      country: "Countryland",
    },
    vendorType: "CONTRACTOR",
  },
  {
    id: 3,
    name: "GHI Enterprises",
    email: "ghi@enterprises.com",
    phone: 5555555555,
    address: {
      street: "789 Oak Street",
      city: "Villageville",
      state: "NEW YORK",
      country: "Countryland",
    },
    vendorType: "SUPPLIER",
  },
  {
    id: 4,
    name: "LMN Solutions",
    email: "lmn@solutions.com",
    phone: 1112223333,
    address: {
      street: "987 Maple Avenue",
      city: "Hamletville",
      state: "FLORIDA",
      country: "Countryland",
    },
    vendorType: "DISTRIBUTOR",
  },
  {
    id: 5,
    name: "PQR Industries",
    email: "pqr@industries.com",
    phone: 4445556666,
    address: {
      street: "654 Pine Road",
      city: "Metropolis",
      state: "ALASKA",
      country: "Countryland",
    },
    vendorType: "SERVICE_PROVIDER",
  },
  {
    id: 6,
    name: "DEF Manufacturing",
    email: "def@mfg.com",
    phone: 7778889999,
    address: {
      street: "321 Cedar Lane",
      city: "Villageland",
      state: "ARIZONA",
      country: "Countryland",
    },
    vendorType: "OTHER",
  },
  {
    id: 7,
    name: "UVW Enterprises",
    email: "uvw@enterprises.com",
    phone: 6667778888,
    address: {
      street: "543 Oak Avenue",
      city: "Citytown",
      state: "ILLINOIS",
      country: "Countryland",
    },
    vendorType: "DISTRIBUTOR",
  },
  {
    id: 8,
    name: "RST Solutions",
    email: "rst@solutions.com",
    phone: 2223334444,
    address: {
      street: "876 Elm Lane",
      city: "Hamletville",
      state: "COLORADO",
      country: "Countryland",
    },
    vendorType: "SUPPLIER",
  },
  {
    id: 9,
    name: "JKL Corporation",
    email: "jkl@corp.com",
    phone: 8889990000,
    address: {
      street: "789 Maple Avenue",
      city: "Citytown",
      state: "MICHIGAN",
      country: "Countryland",
    },
    vendorType: "SERVICE_PROVIDER",
  },
  {
    id: 10,
    name: "MNO Services",
    email: "mno@services.com",
    phone: 3334445555,
    address: {
      street: "234 Pine Road",
      city: "Villageland",
      state: "OREGON",
      country: "Countryland",
    },
    vendorType: "OTHER",
  },
];

module.exports = { VendorList };
